apiVersion: v1
kind: ConfigMap
metadata:
  name: wiz-app-config
  namespace: wiz-app
data:
  # This will be populated by the pipeline with the actual MongoDB IP
  MONGODB_URI: "mongodb://wizapp:WizApp2024!@MONGODB_IP:27017/wiz-opportunities"
  SECRET_KEY: "wizsecretkey123"
